### ISSUE TITLE
Asynchronous listeners to events

### ISSUE THREAD

**Issue by felipecwb** [PHPFluent/EventManager#5]
I was interested in testing EventManager to dispatch Async Operations.

So I made this draft: 
branch: [felipecwb/EventManager/experimental/asyncExecution](https://github.com/felipecwb/EventManager/tree/experimental/asyncExecution)
commit: https://github.com/felipecwb/EventManager/commit/e2c4aabf34776682311119dd703312d6aadd497e

work fine with [Arara\Process](https://github.com/arara/process), 
and pthreads extension.

sample:
[pthreads](https://github.com/felipecwb/EventManager/blob/experimental/asyncExecution/sample/sample-5.php) 
[Arara\Process](https://github.com/felipecwb/EventManager/blob/experimental/asyncExecution/sample/sample-6.php)

**Comment by henriquemoody** [comment]
I took a look on that but unfortunately I don't have too much time right now, but I will try to take a more arcuated look later. :smile:

**Comment by kinncj** [comment]
@felipecwb, why do you need a Factory instead of just inject the Listener?
I don't think it is the EventManager's responsibility to build objects instead of just receive them.

BTW, nice usage of PThread AND Arara :+1: 

PS: My only concern is about the factory, only.

**Comment by kinncj** [comment]
Comments made at: https://github.com/felipecwb/EventManager/commit/e2c4aabf34776682311119dd703312d6aadd497e
